// <auto-generated />
using ActivityReceiver.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ActivityReceiver.Migrations.ActivityReceiverDb
{
    [DbContext(typeof(ActivityReceiverDbContext))]
    partial class ActivityReceiverDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ActivityReceiver.Models.Answer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<int?>("HesitationDegree");

                    b.HasKey("ID");

                    b.ToTable("Answsers");
                });

            modelBuilder.Entity("ActivityReceiver.Models.AnswerRecord", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AnswserID");

                    b.Property<DateTime?>("EndDate");

                    b.Property<int>("QusetionID");

                    b.Property<DateTime>("StartDate");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.ToTable("AnswserRecords");
                });

            modelBuilder.Entity("ActivityReceiver.Models.Movement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnswerRecordID");

                    b.Property<int>("Index");

                    b.Property<bool>("IsFinished");

                    b.Property<int>("State");

                    b.Property<int>("Time");

                    b.Property<int>("XPosition");

                    b.Property<int>("YPostion");

                    b.HasKey("ID");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("ActivityReceiver.Models.Question", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Division");

                    b.Property<int>("EditorID");

                    b.Property<int>("Level");

                    b.Property<string>("Remark");

                    b.Property<string>("SentenceEN");

                    b.Property<string>("SentenceJP");

                    b.HasKey("ID");

                    b.ToTable("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
